### ISSUE TITLE
🧠 Logic: 📪 `bech32_address/2` predicate

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#295]
## 📝 Purpose

In the `logic` module, purpose an utility function to manipulate bech32 address. 

## 🧪 Expected behavior

`bech32_address/2` is a predicate that convert a bech32 encoded string into base64 bytes and give the address prefix or convert a prefix and base64 encoded bytes to bech32 encoded string. The signature is as follow:

```prolog
bech32_address(-Address, +Bech32)
bech32_address(+Address, -Bech32)
bech32_address(+Address, +Bech32)
```

Where:
  - `Address` is a pair containing HRP (Human-Readable Part) containing the address prefix and the list of integers between 0 and 255 (byte) that represent the base64 encoded bech32 address string. Represented like this : `-(HRP, Address)`
  - `Bech32` is an Atom or string representing the bech32 encoded string address 

## 🎯 Example

```
bech32_address(-(Hrp, Address), 'okp415wn30a9z4uc692s0kkx5fp5d4qfr3ac7sj9dqn').
```

Give : 
```json
{
    "Hrp":     "okp4",
    "Address": "[163,167,23,244,162,175,49,162,170,15,181,141,68,134,141,168,18,56,247,30]",
}
```

## ✅ Acceptance Criteria

- [ ] The predicate is implemented according to the described behavior and examples
- [ ] The predicate passes all test cases
- [ ] Any related documentation is updated

## 🔗 Related predicates

- `hex_bytes/2` : #292

**Comment by ccamel** [comment]
Thanks @bdeneux.

The given signature of the `bech32_address predicate` is not exhaustive as it only includes two of the possible variants. For example, another variant that could be supported is `bech32_address(-HRP, +Address, +Bech32) is det`, along with other possible combinations.

I think, it is possible to design the `bech32_address` predicate with 2 arguments: a pair or tuple of the HRP prefix and address, and the Bech32 atom. This approach could offer greater convenience and for me, it makes sense to "bundle" the `HRP` and `address` into a pair or tuple since they are closely related. But we can discuss this.

**Comment by bdeneux** [comment]
~~Yes, you're right, I forgot this variant. There is also `bech32_address(+HRP, -Address, +Bech32) is det`. I will add it in the issue description. Thanks.~~

That seems a good idea to represent the `Address` by a pair of `HRP` and `address`. 

So I suggest this new signature 
```prolog
bech32_address(-Address, +Bech32)
bech32_address(+Address, -Bech32)
bech32_address(+Address, +Bech32)
```

Where `Address` is a pair of `HRP` and `address`.

**Comment by ccamel** [comment]
That's perfect! :+1:
