### ISSUE TITLE
🤑 Implements Token model

### ISSUE THREAD

**Issue by amimart** [okp4/okp4d#433]
## Purpose

Since the publication of the new [Token model](https://docs.okp4.network/whitepaper/token-model), we need to implement it in the software.

## Considerations

Here are some ideas that should be considered regarding the implementation, and that of course can/must be discussed:

### `x/mint` module

Since this module name is first a standard cosmos sdk module, block explorers and other UIs apps rely on the specification coming from the cosmos sdk, which is conflicting with ours. So it may be relevant to implement inflation mechanisms in a different module name, for example: `x/inflation`. This way, block explorers won't be able to display wrong informations.

Please don't hesitate to mention any considerations you would be regarding implementation.

**Comment by tpelliet** [comment]
## Implementation alternative

Following a discussion with @bdeneux, it seems there's another way to implement the Token model.

### Current mechanism

If we think in stages, at the end of each daily epoch you should have:

1. Calculation of SRT (based on bonding)
2. Distribution of the tax pool, supplemented by the mint to reach the SRT if tax pool < SRT. In this case SRT = tax pool + mint.
3. If tax pool > SRT then SRT is distributed from the tax pool and the excess remaining after distribution (= tax pool - SRT) is burnt.


### Alternative

The alternative removes the tax pool by:
- **Burning all taxes**
- **Minting all staking rewards**

This provides a similar end result.
If for exemple during a day there is 2 tokens collected as tax and the staking reward should be 10, it is _almost_ the same to:
- Redistribute 2 and mint 8, or
- Burn 2 and mint 10

We have the same end-result, with additional benefits:
- No need to manage daily epochs, everything is on a per-block basis. Each workflow includes a tax that is burnt.
- There is no need for a pool of tokens to be collected and redistributed.
- We can use the cosmos `x/mint` _"almost"_ as it is. The minting only depends on two variables: total supply & bonding ratio.
- It may also be a good legal argument in case tokens holders are accused to get some revenue from illegal activity that may happen in the network. With a burn/mint mechanism this argument is harder to make than with a redistribution mechanism.

Regarding the params it's pretty similar, everything is simply converted on a per year basis instead of daily:

```
- Params
    - inflationCoef : 7.3
    - boundingAdjustment: 2.5
    - targetBoundingRatio : 0.66
    - blocksPerYear : 6307200 **Considering 5s per / block ** (or 6311520 if 365.25 days per year..)
- Minter :
    - inflation
```

Last note, the implementation should consider the ability to define multiple taxes, with different destinations: burn, address or community pool.

Proposed workflow tax parameters for mainnet launch:

- 2% burnt
- 0.5% for association treasury
- 0.5% for community pool

**Comment by ccamel** [comment]
I broadly agree with the alternative approach of a block calculation proposed by @tpelliet. However Shifting from a daily basis mechanism to a per-block basis is not a mere change in frequency; it introduces slightly differences in how values compound and adjust over time. Indeed, with a per-block mechanism, any changes (like rewards, burns, or mints) are compounded every block. Over the course of a day, these small changes can accumulate and diverge from a single daily adjustment. If rewards are distributed on a block-by-block basis, this can lead to specific behaviors that are different from daily distributions. Before going any further with the implementation, I'd like to see this frozen in the whitepaper on approval. So let it be written so let it be done.

> Last note, the implementation should consider the ability to define multiple taxes, with different destinations: burn, address or community pool.

Yes. So relevant. :relieved:

**Comment by tpelliet** [comment]
Let us recap and agree collectively on the approach before editing the whitepaper.

We have 3 types of actions regarding tokens: `transfer` `mint` `burn`
And we have 2 different taxes to be enforced on the `Pactum` side:
- A 2% tax to compensate for inflation, this one will be `burn`t
- A 1% tax for the commuity pool, this one will be `transfer`ed (the transfer destination address and tax value should be editable through governance)

When a workflow is initiated, X provisionned tokens are `transfer`ed from the consumer to the escrow.
Then, the execution price Y is determined:
- (X-Y) is `transfer`ed back to the consumer
- Y*0.97 is `transfer`ed to the providers
- Y*0.02 is `burn`t
- Y*0.01 is `transfer`ed to the community pool

The `mint` is calculated on a per-block basis and is completely independant from any workflow that may or may not occur. Taxes don't influence the `mint`. The only variable on the `mint` side is the bonding ratio. The rest are fixed parameters that can only be changed by governance.

Do you agree @ccamel? Do you need anything else to go forward on the implementation @bdeneux?

**Comment by bdeneux** [comment]
Thanks @tpelliet for this clarification. So at this moment, the mint module's PR (#439) is ready for review since, like you say, it's completely independent from workflow and taxes. 

I'm just wondering about the accuracy of the transfer, depending on the workflow cost, taking a small percentage of tokens (2% for burn and 1% for the community pool) on the cost of the workflow can cause trouble if the precision of `uknow` is not enough, we would be forced to either have a minimum or zero amount to distribute or burn. But it depend of the average workflow cost, I think we need to consider this.

**Comment by tpelliet** [comment]
Interesting, yes it needs to be considered.

Let's do a quick worst case scenario:
1. Token value get very high, let say 5 billion valuation: $25 per token.
2. A very small workflow with a $0.01 value is initiated: 0.01/25=0.0004 `KNOW` (400 `uknow`). 
3. The 1% tax is then 4 `uKNOW`

Even with such extremes, the tax doesn't go to zero. 
It seems that if the result of the tax calculation is not an integer it can be truncated without significative impact on the tax burnt/collected.
