### ISSUE TITLE
🧠 Logic: 🔑 `verify_signature/4` predicate

### ISSUE THREAD

**Issue by amimart** [okp4/okp4d#458]
## Idea

In the logic module, implements a new Prolog custom predicate allowing to verify a digital signature.

## Context

When designing governance rules through Prolog evaluated by the logic module, the ability to check a cryptographic signature through a dedicated predicate could be useful in the perspective where an authority issue some verifiable credentials and one needs to check that these credentials have truly been signed by this trusted authority.

## Spec Proposal

Predicate signature: `verify_signature(Alg, PubKey, Msg, Sig) is det`.

Where:
- `Alg`: The algorithm used to sign the message.
- `PubKey`: The public key derived from the private key who signed the message.
- `Msg`: The message who has been signed.
- `Sig`: The message signature.

Regarding the supported algorithms I think we can give a priority to `ed25519`.

**Comment by ccamel** [comment]
To be in line with the [form of predicates provided by SWI Prolog](https://www.swi-prolog.org/pldoc/man?section=crypto-signatures) in that matter, I'd suggest the following naming scheme:

```
<algo>_verify(+Key, +Data, +Sig, +Options) is semidet
```

Note that the predicate family is semidet (semi-deterministic) since the predicate has the potential to either succeed once or fail.

For instance:


```
eddsa_verify(+Key, +Data, +Sig, +Options) is semidet
```

where `Options` is:
- `type( ed25519 )`.

And:

```
secp_verify(+Key, +Data, +Sig, +Options) is semidet
```

where `Options` is:
- `type(secp256k1)` or `type(secp256r1)`.
